### ISSUE TITLE
Centos7 ossec-puppet breaks idempotency by errorously restarting ossec-hids(-agent)

### ISSUE THREAD

**Issue by christophkobe** [wazuh/ossec-puppet#13]
After installing ossec-hids and ossec-hids, puppet idempotency was broken due to ongoing restarts of the corresponding services on all hosts except on one old centos6 host (e.g. puppet thinks the service is missing and restarts the service).

It seems this is caused by two different reasons:

1. OSSEC Rpm 2.8.3 does not yield proper .service files for systemd, instead the old chkconfig is used (normally not a real issue since this is supported by Centos/RedHat).
2. There seems to be a bug in puppet https:/https://tickets.puppetlabs.com/browse/PUP-2744 that results in the wrong provider is being chosen for RedHat/Centos 7 for legacy services.

These two facts together results in a broken service {} configuration for both agent and server on Centos7/RedHat7.

Solution:
forcing 'provider => redhat' on RedHat/Centos 7 seems to solve the issue.

**Comment by jlruizmlg** [comment]
Hi @christophkobe, 
First of all, thanks for the feedback!
After some test in our lab with CentOS7 we can't reproduce the error, which puppet agent and master  version do you use?

**Comment by christophkobe** [comment]
Puppet Open Source 4.3.2

**Comment by jlruizmlg** [comment]
And your puppet master is under CentOS(Red Hat) or Ubuntu(Debian) and which version? i will try to reproduce the error with your same environment in our lab.

**Comment by christophkobe** [comment]
All Servers run under Centos7, also the puppet master. We have only one type of application node that still needs Centos6 and there everything works as expected.

**Comment by jlruizmlg** [comment]
Perfect @christophkobe thanks i will review and give some feedback as soon as possible.

**Comment by jlruizmlg** [comment]
Hi @christophkobe you are right! after review in your lab we had the same problem.

In `manifests/params.pp` set  `$service_has_status  = false`

and try again, this should be fix the problem.
