### ISSUE TITLE
Configuration file it's not written with concat v2.10

### ISSUE THREAD

**Issue by awainer** [wazuh/ossec-puppet#15]
The configuration file it's not being written to the client when using puppetlabs-concat version 2.1.0, using 1.2.5 works perfectly with the same manifests. 
Using puppet 3.6 on ubuntu 14.04 (both master and agent).

**Comment by jlruizmlg** [comment]
Hi @awainer.  I just tried the same versions and it works OK  in our lab.  Please try to reinstall both modules and if the problem persists, please send us a error trace and any example manifest.

In a couple days we go to upload a new version to [https://forge.puppetlabs.com/wazuh/ossec](https://forge.puppetlabs.com/wazuh/ossec) from this module.

root@puppet:/etc/puppet#cat modules/concat/metadata.json
{
  "name": "puppetlabs-concat",
  "version": "2.1.0",
  "author": "Puppet Labs",
  "summary": "Construct files from multiple fragments.",
  "license": "Apache-2.0",
  "source": "https://github.com/puppetlabs/puppetlabs-concat",
  "project_page": "https://github.com/puppetlabs/puppetlabs-concat",
  "issues_url": "https://tickets.puppetlabs.com/browse/MODULES",
  "dependencies": [
    {"name":"puppetlabs/stdlib","version_requirement":">= 3.2.0 < 5.0.0"}

>Info: Computing checksum on file /var/ossec/etc/ossec.conf
Debug: Evicting cache entry for environment 'production'
Debug: Caching environment 'production' (ttl = 0 sec)
Info: FileBucket got a duplicate file {md5}e814ad44aa659df35e0f60a322f45665
Info: /Stage[main]/Ossec::Server/Concat[/var/ossec/etc/ossec.conf]/File[/var/ossec/etc/ossec.conf]: Filebucketed /var/ossec/etc/ossec.conf to puppet with sum e814ad44aa659df35e0f60a322f45665
Notice: /Stage[main]/Ossec::Server/Concat[/var/ossec/etc/ossec.conf]/File[/var/ossec/etc/ossec.conf]/content: content changed '{md5}e814ad44aa659df35e0f60a322f45665' to '{md5}22d33dbee9bca144497403e066ca6dd3'
Debug: /Stage[main]/Ossec::Server/Concat[/var/ossec/etc/ossec.conf]/File[/var/ossec/etc/ossec.conf]: The container /var/ossec/etc/ossec.conf will propagate my refresh event
Debug: /var/ossec/etc/ossec.conf: The container Concat[/var/ossec/etc/ossec.conf] will propagate my refresh event
Debug: Concat[/var/ossec/etc/ossec.conf]: The container Class[Ossec::Server] will propagate my refresh event
Info: Concat[/var/ossec/etc/ossec.conf]: Scheduling refresh of Service[ossec]

**Comment by awainer** [comment]
I'm sorry, but after upgrading concat again to 2.1.0 I can't reproduce the issue. 
After downgrading to 1.2.5, I had to activate pluginsync, so that's probably the reason it's working now.

Sorry and thanks for looking into this.
