### ISSUE TITLE
Support manage_repo option on client as well

### ISSUE THREAD

**Issue by cudgel** [wazuh/ossec-puppet#2]
Wazuh repos do not work in our environment (Oracle Linux) where releasever is returned as 6Server. Ideally we would like to manage our own mirror of the packages via Spacewalk.

**Comment by jlruizmlg** [comment]
hello cudgel, thank for your suggestion, i will be include the manage_repo option in the client as soon as possible (a couple days).

And about the releasever i go to talk with my coworkers, i think the best option is add 5Server, 6Server, etc,  to the yum repository. what do you think?

**Comment by cudgel** [comment]
That would certainly be a good short-term fix for preventing errors.

**Comment by jlruizmlg** [comment]
ok fix, you have available the module in forge.puppetlabs, thanks for your comments
