### ISSUE TITLE
Mysql schema order issue

### ISSUE THREAD

**Issue by paul-cs** [wazuh/ossec-puppet#29]
Hi there,

In your example at: http://documentation.wazuh.com/en/latest/ossec_puppet.html#ossec-puppet-module
You have:

  mysql::db { 'ossec':
    user     => 'ossec',
    password => 'yourpassword',
    host     => 'localhost',
    grant    => ['ALL'],
    sql      => '/var/ossec/contrib/sqlschema/mysql.schema'
  }

The issue is, some how with the anchors in the ossec::server, mysql is installed before ossec-hids. This means that the schema is NEVER present, so the database never gets any tables. If I add: enforce_sql => true, (which changes its to have refreshtrue =>false) then the second run will create the tables. However any run thereafter generates errors about the tables already existing. I also tried modifying the anchor order in server.pp to make it execute the hids install before mysql, but I can't seem to get that to work.

Also, could you please update activeresponse.erb to have:
  <active-response>
    <command><%= @command_name %></command>
    <location><%= @ar_location %></location>
    <level><%= @ar_level %></level>
<% if !@ar_rules_id.empty? -%>
    <rules_id><% @ar_rules_id.each do |ruleid| -%><%= ruleid %>,<% end %></rules_id>
<% end -%>
    <timeout><%= @ar_timeout %></timeout>
<% if @ar_repeated_offenders != '' -%>
    <repeated_offenders><%= @ar_repeated_offenders %></repeated_offenders>
<% end -%>
  </active-response>

Reason, if the ar_rules_id is empty, I don't want to see the tags. I'm implementing a response where any alert above 9, that has a srcip will call host_deny (this is the default ossec rule). I also changed it so it formats all the lines nicely.

Thanks

**Comment by jlruizmlg** [comment]
Hi @paul-cs let me review that thanks!!

**Comment by jlruizmlg** [comment]
@paul-cs i just update the ar_rules_id thanks for your suggestion, let me review what is the better way to work with the mysql

**Comment by jlruizmlg** [comment]
Hi @paul-cs first at all sorry for the delay in reply your question.
Because mysql use the command ```cat``` to populate the database from a file like you see bellow
```
   if $sql {
      exec{ "${dbname}-import":
        command     => "cat ${sql_inputs} | mysql ${dbname}",
        logoutput   => true,
        environment => "HOME=${::root_home}",
        refreshonly => $refresh,
        path        => '/bin:/sbin:/usr/bin:/usr/sbin:/usr/local/bin',
        require     => Mysql_grant["${user}@${host}/${table}"],
        subscribe   => Mysql_database[$dbname],
        timeout     => $import_timeout,
      }
    }
```
The only way than i found to apply the schema before install is doing through the repository, so other option is populate the schema like this:
```
  mysql::db { 'ossec':
    user     => 'ossec',
    password => 'password',
    host     => '127.0.0.1',
    grant    => ['ALL'],
    sql      => '& curl https://raw.githubusercontent.com/ossec/ossec-hids/v2.8.3/src/os_dbd/mysql.schema'
  }
```
With this option, you will always have the schema no matter  ossec is installed or not.
