### ISSUE TITLE
Addlog for agent

### ISSUE THREAD

**Issue by paul-cs** [wazuh/ossec-puppet#30]
If I want to add a local log to an agent (as it appears that you cannot do this using the shared agent conf), I cannot use:

ossec::addlog { 'monitorLogFile1':
        logfile => '/var/log/messages',
        logtype => 'syslog'
    }

Because it has:

 notify  => Service[$ossec::params::server_service]

Which obviously isn't defined for a client.

I'm not an expert, and maybe this isn't the way to do it. But if it is, can you please remove the notify.

Thanks

**Comment by jlruizmlg** [comment]
Hi @paul-cs first at all, sorry for the delay, we need this notify to restart the manager service after any log file is added or deleted in ossec.conf to apply the changes, let me review, probably the best way is add a condition to know if the log is for the agent or manager and restart the correct service, make sense for you??

regards.

**Comment by jlruizmlg** [comment]
Updated the addlog manifest with the next code
```
#Define a log-file to add to ossec
define ossec::addlog(
  $logfile,
  $agent_log = false,
  $logtype = 'syslog',
) {
  require ossec::params
# Issue #30
  if $agent_log
  {
    $ossec_notify = Service[$ossec::params::agent_service]
  } else {
    $ossec_notify = Service[$ossec::params::server_service]
  }


  concat::fragment { "ossec.conf_20-${logfile}":
    target  => $ossec::params::config_file,
    content => template('ossec/20_ossecLogfile.conf.erb'),
    order   => 20,
    notify  => $ossec_notify
  }

}
```

**Comment by seefood** [comment]
That's kinda ugly, it leaves the setting of `$agent_log` to the user instead of encapsulating this in the code. Shall I fix this and make a PR?

**Comment by jlruizmlg** [comment]
Hi @seefood you are right, i was thinking in review in the file ```/var/ossec/etc/ossec-init.conf``` what kind of installation (manager or agent) and restart the specific service, in this case we don't need to use ```$agent_log```.

And of course, if you can fix please send the PR, thanks for your comments!
