### ISSUE TITLE
ossec_scanpaths

### ISSUE THREAD

**Issue by drequena** [wazuh/ossec-puppet#33]
Well, this is more of a question than a issue.
I'm not using hiera, I'm using foreman.
How do I suppose to overwrite $ossec_scanpaths? I tried doing

["/etc,/bin,/sbin"]
["/etc","/bin","/sbin"]

and a lot of other options, but without success, since "path" "report_changes" and "realtime" always got the wrong values.

ps: using Puppet 3.8 here.

**Comment by jlruizmlg** [comment]
Hi @drequena is this issue fixed? Can you explain your solution?

**Comment by drequena** [comment]
A few days ago, my solution was to alter the 10_ossec_agent.conf.erb file and force report_changes to "yes" and realtime to "no". By doing this, I just had to send a simple array with the default Linux directories. (I used the "kernel" fact as a classifier on foreman).

Today, I realized that, when you want to override a class parameter on foreman, you can set the "key type" to YAML. By doing this, you can specify values just like hiera, like:

ossec::client:
 ossec_scanpaths:
   report_changes: yes
   realtime: no
   path: '/etc'

This is by far the best solution, since now I don't need to maintain a "forked" erb file.
