### ISSUE TITLE
ossec::repo - use repo key hash.

### ISSUE THREAD

**Issue by drequena** [wazuh/ossec-puppet#34]
Every time I use ossec-puppet module on a server I must exclude it from my proxy rule, so the apt module can add the repository key.
Reading through the module, I've notice that you are using strings on apt::source to send the $key and $key_source.
It would be good to change that and use a hash, just like the APT module adverts, so we can set a proxy and the key add process could be done without direct internet access.

**Comment by jlruizmlg** [comment]
hi @drequena let me review this

**Comment by jlruizmlg** [comment]
Fixed in the commit https://github.com/wazuh/ossec-puppet/commit/007035f0b0777202909381d63aa91d97f52e9ad5 thanks for your contribution @drequena
