### ISSUE TITLE
security issues

### ISSUE THREAD

**Issue by tobowers** [wazuh/ossec-puppet#41]
If my tone ever sounds harsh, it is not intended. I just want to document a couple of security issues so that we can all work through them.

<details>
<summary>https://github.com/wazuh/ossec-puppet/blob/master/manifests/repo.pp#L75-L82</summary>
        yumrepo { 'ossec':
          descr    => 'WAZUH OSSEC Repository - www.wazuh.com',
          enabled  => true,
          gpgkey   => 'http://ossec.wazuh.com/key/RPM-GPG-KEY-OSSEC',
          baseurl  => 'http://ossec.wazuh.com/el/$releasever/$basearch',
          priority => 1,
          protect  => false,
        }
</details>

1. The gpgkey being http (no ssl) effectively means that a third party can provide alternative versions of software to a repository requester.
1. The `priority => 1` and `protect => false` effectively mean that the wazuh repository can provide updates to other packages on the system. In fact, it will be the highest priority source of truth for other packages.

The combination of those two things is pretty scary... it would allow a 3rd party to provide "updated" packages for anything it wanted and the system would be totally OK with it since it's signed.

**Comment by jlruizmlg** [comment]
Hi @tobowers you are totally right, this code is here from the original puppet project from jgazeley and to be honest, I did not realize.

**Comment by jlruizmlg** [comment]
After merge your pull request #42 this issue should be fixed.
Thanks again @tobowers for your contribution.
