### ISSUE TITLE
Feature request - quiet down the torrents of Emails

### ISSUE THREAD

**Issue by seefood** [wazuh/ossec-puppet#44]
OSsec seems to be sending me way too many emails. I limited it to level 5 and still it sends me unwanted level 10 alerts because there are overrides in the individual rules.

What's the right approach in such a case? can I turn of certain rules programmatically without actually overwriting rule files? I could not find any such option in the documentation od OSSEC and I'd love to use this module to set such options instead of going over all the rules with a fine comb. What's the recommended course of action on this?

**Comment by jlruizmlg** [comment]
Hi @seefood, You can not limit the alerts to a specific level; you can only specify what is the minimum level alert you want to receive.. as you have selected level 5, you will receive ALL alerts from 5 and above.  

Our recommendation for a standard environment is level 7 or higher.

On the other hand, you always will take alerts from some rules no matter what level you use as following example:
```
  <rule id="503" level="3">
    <if_sid>500</if_sid>
    <options>alert_by_email</options>
    <match>Agent started</match>
    <description>Ossec agent started.</description>
    <group>pci_dss_10.6.1,pci_dss_10.2.6,</group>
  </rule>
```

This rule has level 3, but has the option ```<options>alert_by_email</options>```, no matter if you have alert level to 5 or 7, you always will take this alert.

If you don't like this, you need to overwrite this alert in the file ```etc/rules/local_rules.xml``` and remove the line ```<options>alert_by_email</options>```

Something similar to the following example:

```
<group name="ossec,">
  <rule id="503" level="3" overwrite="yes">
    <match>Agent started</match>
    <description>Ossec agent started.</description>
    <group>pci_dss_10.6.1,pci_dss_10.2.6,</group>
  </rule>
</group>
```

But looking the module, seems like we don't have the file ```local_rules.xml``` as a template, I am working to add this option as soon as possible.

**Comment by seefood** [comment]
got it. so my only course of action now is to overwrite the rule files. seems legit.

**Comment by jlruizmlg** [comment]
Hi @seefood in the last version v2.0.16 you have available the template ```local_rules.xml``` to manage your own rules through puppet.
