### ISSUE TITLE
puppet forge says this works with Centos 7 but the package names don't match

### ISSUE THREAD

**Issue by SyBernot** [wazuh/ossec-puppet#45]
Notice: /Stage[main]/Profile::Minimal/Notify[puppet agent]/message: defined 'message' as 'puppet agent'
Error: Execution of '/bin/yum -d 0 -e 0 -y list ossec-hids-agent' returned 1: Error: No matching Packages to list
Error: /Stage[main]/Ossec::Client/Package[ossec-hids-agent]/ensure: change from absent to present failed: Execution of '/bin/yum -d 0 -e 0 -y list ossec-hids-agent' returned 1: Error: No matching Packages to list

it should be looking for ossec-hids-client

os => {"name"=>"CentOS", "family"=>"RedHat", "release"=>{"major"=>"7", "minor"=>"2", "full"=>"7.2.1511"}, "lsb"=>{"distcodename"=>"Core", "distid"=>"CentOS", "distdescription"=>"CentOS Linux release 7.2.1511 (Core) ", "release"=>":core-4.1-amd64:core-4.1-noarch:cxx-4.1-amd64:cxx-4.1-noarch:desktop-4.1-amd64:desktop-4.1-noarch:languages-4.1-amd64:languages-4.1-noarch:printing-4.1-amd64:printing-4.1-noarch", "distrelease"=>"7.2.1511", "majdistrelease"=>"7", "minordistrelease"=>"2"}}
osfamily => RedHat

**Comment by jlruizmlg** [comment]
Hi @SyBernot if you are running the lastest Puppet version should be a repository under ``/etc/yum.repo`` named ```ossec.repo``` with the next content

```
[ossec]
name=WAZUH OSSEC Repository - www.wazuh.com
baseurl=http://ossec.wazuh.com/el/$releasever/$basearch
enabled=True
gpgkey=file:///usr/src/ossec/RPM-GPG-KEY-OSSEC
```

In this repository the agent name is ```ossec-hids-agent```

Can you please review this repository and copy the content?

**Comment by SyBernot** [comment]
I have 
```
[ossec]
name=WAZUH OSSEC Repository - www.wazuh.com
mirrorlist=http://updates.atomicorp.com/channels/mirrorlist/ossec/centos-$releasever-$basearch
enabled=true
gpgkey=file:///src/ossec/RPM-GPG-KEY-OSSEC
priority=1
baseurl=http://ossec.wazuh.com/el/$releasever/$basearch
```

So I see whats happening now, puppet doesn't look at the contents of the repo file it just makes sure it's there.  This is an upgrade of an existing install from the older code base.  So to get this to chooch I need to blow out the existing repo, remove the existing packages and do a yum clean all to get back on track with a puppet run. I have about 100 clients to do this on, thank goodness for puppet and small bash scripts. 

Thanks!

**Comment by jlruizmlg** [comment]
Hi @SyBernot yes, we just fix this error, you have the update in puppet forge.

```gpgkey=file:///src/ossec/RPM-GPG-KEY-OSSEC``` is wrong should be
```gpgkey=file:///usr/src/ossec/RPM-GPG-KEY-OSSEC```.

We also add a fix to the template ossec.conf if you are using ossec-hids 2.8.3 now you have the templates for local_rules.xml and local_decoders.xml

Sorry about that

**Comment by SyBernot** [comment]
The problem was it was pulling from atomic (the old code base was using that) 
I'll deal with it with a strategically placed one shot cron It will all be right by lunch. I appreciate the sanity check I was going bonkers trying to figure out all the changes from the last couple of years.

**Comment by jlruizmlg** [comment]
You are welcome, please let us know if we can help you with something else.

http://documentation.wazuh.com/en/latest/ossec_puppet.html

You can found all documentation about this module.
