### ISSUE TITLE
Tag v.2.0.18 not released on github?

### ISSUE THREAD

**Issue by bruberg** [wazuh/ossec-puppet#49]
https://forge.puppet.com/wazuh/ossec/readme says tag 2.0.18 is released, but the github repo only offers up to v.2.0.17. Judging from the changelog, the missing decoder seems to have been added in 2.0.18 / master. Shouldn't the tags match between forge.puppet.com and github.com?

**Comment by jlruizmlg** [comment]
Hi @bruberg you are right, let me check this difference.

**Comment by jlruizmlg** [comment]
Thanks @bruberg, just release the v.2.0.18 with this change.
