### ISSUE TITLE
Tagged Releases Now Have an Extra Dot

### ISSUE THREAD

**Issue by johnzimm** [wazuh/ossec-puppet#52]
There have been a couple of conventions for tagging releases in puppet modules.

- 2.0.18
- v2.0.18

The last couple of releases of this modules has switched to a third...

 - v.2.0.18

Just noticed when I went to look for updates to modules in my Puppetfile.  Is this intentional?

**Comment by jlruizmlg** [comment]
Hi @johnzimm You are right, was my mistake in Github! I will fix now.

**Comment by jlruizmlg** [comment]
Well after a tiny mess in my side, I change the name, but the tags are not easy to change.
if I try to change the tag name always try to release the actual master, after this release, we will continue with the tag similar than forge 2.xx.xx like in the forge.
Make sense for you @johnzimm ???

**Comment by jlruizmlg** [comment]
Last release published with 2.0.19 tag.
