### ISSUE TITLE
server.pp and client.pp don't accept a package version parameter

### ISSUE THREAD

**Issue by MatthewRBruce** [wazuh/ossec-puppet#55]
Since server.pp and client.pp don't accept a package version number as a parameter it makes upgrading the packages more difficult as the manifests only ensure that any version of the packages are installed

**Comment by jlruizmlg** [comment]
hi @MatthewRBruce your pull request #57 it's to fix this issue right??

**Comment by MatthewRBruce** [comment]
Yup!

**Comment by jlruizmlg** [comment]
Fixed in the pull request #57 made for your self! Thanks for your contribution as always!
