### ISSUE TITLE
puppet module to use the Wazuh fork of OSSEC?

### ISSUE THREAD

**Issue by TravellingGuy** [wazuh/ossec-puppet#6]
I recently switched to your puppet module (from jgazeley's one on the forge) and was kind of expecting that it might use the Wazuh fork of OSSEC, but it appears that that is not the case, as I'm not seeing any of the Wazuh specific stuff.

Do you plan on providing a puppet module that will use your Wazuh fork of OSSEC? 

(As an aside, I had submitted a few pull requests to jgazeley's module, and I see one or two of them have been merged here as well. Cool. I've got another pull request lined up I'll send your way probably this week.)

**Comment by jlruizmlg** [comment]
Hi @TravellingGuy first of all thanks for your contribution to the community!  some code from this module is from jgazeley's and from you as well, we appreciate your contributions.
Right now we are working on new packages, so We hope in few days we can give both options, Ossec or Wazuh fork in this module.

**Comment by seefood** [comment]
so in the meantime, I should be installing the ossec_ruleset.py manually and running it? Unless I'm missing something, from a quick browse in the module I don't see puppet doing this for me.

**Comment by jlruizmlg** [comment]
Hi @seefood this module install OSSEC (2.8.3), we are working in release a new module to use Wazuh fork, but if you install ossec_ruleset.py manually it should work.

**Comment by seefood** [comment]
and changing the package names in params to wazuh-agent and wazuh-manager should just work as well?

**Comment by jlruizmlg** [comment]
Those packages are only available to CentOS and RedHat, we are finishing the Debian and Ubuntu version, should be available soon.
After the Ubuntu & Debian release we will create an other puppet module for wazuh fork

**Comment by seefood** [comment]
Well, lucky me, I'm running on CentOS. How about a public beta? :)

**Comment by toddmichael** [comment]
Curious on the status of the Debian packages. I was pleasantly surprised to find Wazuh fork CentOS packages the other day so started rewriting for this only to find that there was no analog for Debian family. I need to support RHEL, Amazon, Debian and Ubuntu.  If this is on the horizon I'll wait.  Otherwise, I'll switch gears.  Thanks much.  Love the Wazuh project.

**Comment by jlruizmlg** [comment]
Hi @toddmichael we are working in the Debian and Ubuntu packages and we are going to release the first version in the next week or so.
On the other hand we are working on a independent Puppet module for Wazuh, this way people who like to use OSSEC can continue with this module, and those who like to use Wazuh can install the new module.

Our plan is to continue supporting both OSSEC versions.

**Comment by elisiano** [comment]
Unless I'm missing something, I still can't find any version of the wazuh module.
Would making a change like @TravellingGuy suggested (ie: have parameters for the packages names) fix this or is there more to it?

**Comment by jlruizmlg** [comment]
hi @elisiano we are working in a new module compatible with Wazuh our plan is release the first version the next Monday 24.

This module will be very similar than the actual ossec-puppet but will include Wazuh repositories, the installation from wazuh-manager and wazuh-agent (Linux and Windows).

**Comment by elisiano** [comment]
OK thanks, looking forward to it.

**Comment by elisiano** [comment]
[drumroll](https://youtu.be/itAOGRiYRLI)...

**Comment by jlruizmlg** [comment]
@elisiano you can take a look from the new module [here](https://github.com/wazuh/wazuh)

**Comment by jlruizmlg** [comment]
@elisiano @TravellingGuy @toddmichael @seefood you can take a look from the new module [here](https://github.com/wazuh/wazuh)

Thanks for your patience!! Too much things to do!! and continue improving!!
