### ISSUE TITLE
gpg key download via http

### ISSUE THREAD

**Issue by thedawidbalut** [wazuh/ossec-puppet#66]
Hello again,

I've noticed that at https://github.com/wazuh/ossec-puppet/blob/master/manifests/repo.pp#L32 you're downloading gpg key via http, which because of MiTM possibility defeats the purpose of having gpg verification at all. Can you switch to https? I've verified that key can be downloaded from wazuh website via https without any problems.

Cheers!

**Comment by jlruizmlg** [comment]
Hi @thedawidbalut you are right, in the push 1ffc0a8291d0d6b4885c3cd653b944eee4f29a27 we update the all URL's to work with https.

Thanks for your feedback.

**Comment by thedawidbalut** [comment]
awesome, thanks!
