### ISSUE TITLE
rootcheck set to true, but with no options in puppet

### ISSUE THREAD

**Issue by sc-chad** [wazuh/ossec-puppet#71]
This is on Amazon Linux in AWS:

In the latest release the defaults are setting:

`ossec_rootcheck == true` on the server

But then in the template for /var/ossec/etc/ossec.conf (10_ossec.conf.erb):
```<% if @ossec_rootcheck == false then -%>
  <rootcheck>
    <disabled>yes</disabled>
  </rootcheck>
<% else -%>
  <rootcheck>
  <%- if @ossec_rootcheck_frequency then -%>
    <frequency><%= @ossec_rootcheck_frequency %></frequency>
  <%- end -%>
  <%- if @ossec_rootcheck_checkports == false then -%>
    <check_ports>no</check_ports>
  <%- end -%>
  <%- if @ossec_rootcheck_checkfiles == false then -%>
    <check_files>no</check_files>
  <%- end -%>
  </rootcheck>
<% end -%>
```

Which basically just adds:
```
  <rootcheck>
  </rootcheck>
```
Into the file causing ossec-hids not to be able to start.

**Comment by jlruizmlg** [comment]
Hi @sc-chad you are right, fixed in the commit https://github.com/wazuh/ossec-puppet/commit/5e9332b393f63e82859dbed8f1904d2e97b9901a

**Comment by jlruizmlg** [comment]
Sorry for close the issue, please try and let us know if works for you.
